export const GET_SALES_STATUSES = 'GET_SALES_STATUSES';
export const GET_SALES_STATUS = 'GET_SALES_STATUS';
export const ADD_SALES_STATUS = 'ADD_SALES_STATUS';
export const EDIT_SALES_STATUS = 'EDIT_SALES_STATUS';
export const DELETE_SALES_STATUS = 'DELETE_SALES_STATUS';
export const TOGGLE_STATE = 'TOGGLE_STATE';
export const ERROR_STATE = 'ERROR_STATE';