export const ADD_ROLE = 'ADD_ROLE'
export const DISPLAY_ROLES = 'DISPLAY_ROLES'
export const GET_ROLE = 'GET_ROLE'
export const GET_PER_ROLE = 'GET_PER_ROLE'
export const EDIT_ROLE = 'EDIT_ROLE'
export const DELETE_ROLE = 'DELETE_ROLE'
export const TOGGLE_STATE = 'TOGGLE_STATE'
export const ERROR_STATE = 'ERROR_STATE'