export const ADD_BANK_ACCOUNT = 'ADD_BANK_ACCOUNT'
export const GET_BANK_ACCOUNTS = 'GET_BANK_ACCOUNTS'
export const DELETE_BANK_ACCOUNT = 'DELETE_BANK_ACCOUNT'
export const GET_DEFAULT_BANK_ACCOUNT = 'GET_DEFAULT_BANK_ACCOUNT'