export const SHOW_ALL_ADMIN_COMMENTS = 'SHOW_ALL_ADMIN_COMMENTS';
export const GET_ADMIN_COMMENTS = 'GET_ADMIN_COMMENTS';
export const ADD_ADMIN_COMMENT = 'ADD_ADMIN_COMMENT';
export const EDIT_ADMIN_COMMENT = 'EDIT_ADMIN_COMMENT';
export const DELETE_ADMIN_COMMENT = 'DELETE_ADMIN_COMMENT';
export const TOGGLE_STATE = 'TOGGLE_STATE';
export const ERROR_STATE = 'ERROR_STATE';